name: Go package

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:
    strategy:
      matrix:
        os:
         - ubuntu-latest
        #  - windows-latest
        #  - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: go build -v ./...

      - name: Run vet & lint
        run: |
          go vet .
          statticcheck ./...

      - name: Test
        run: go test -v ./...